name       : python-magic
version    : 0.4.15
release    : 4
source     :
    - https://files.pythonhosted.org/packages/84/30/80932401906eaf787f2e9bd86dc458f1d2e75b064b4c187341f29516945c/python-magic-0.4.15.tar.gz : f3765c0f582d2dfc72c15f3b5a82aecfae9498bd29ca840d72f37d7bd38bfcd5
license    : MIT
component  : system.base
summary    : Python interface for libmagic
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
description: |
    This module uses ctypes to access the libmagic file type identification library. It makes use of the local magic database and supports both textual and MIME-type output.
install    : |
    %python_install
