name       : python-magic
version    : 0.4.22
release    : 7
source     :
    - https://files.pythonhosted.org/packages/26/60/6d45e0e7043f5a7bf15238ca451256a78d3c5fe02cd372f0ed6d888a16d5/python-magic-0.4.22.tar.gz : ca884349f2c92ce830e3f498c5b7c7051fe2942c3ee4332f65213b8ebff15a62
license    : MIT
component  : system.base
summary    : Python interface for libmagic
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
description: |
    This module uses ctypes to access the libmagic file type identification library. It makes use of the local magic database and supports both textual and MIME-type output.
install    : |
    %python_install
    %python3_install
